name: Terraform Deploy on Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"

      - name: Initialize Terraform
        run: terraform init

      - name: Download Terraform plan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan-pr-${{ github.sha }}

      - name: Apply Terraform changes from PR plan
        run: terraform apply -auto-approve tfplan
