name: Terraform Deploy on Main

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"

      - name: Initialize Terraform
        run: terraform init

      - name: Generate new Terraform plan for apply
        run: terraform plan -no-color -out=tfplan

      - name: Apply Terraform changes from PR plan
        run: terraform apply -auto-approve tfplan
