name: Terraform

on:
  # push:
  #   branches:
  #     - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      # Check out repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan > plan.txt
      
      - name: Parse Plan with Node.js
        run: node scripts/parse-plan.js
      
      - name: Merge PR if safe
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo "Merging PR #$PR_NUMBER"
          gh pr merge $PR_NUMBER --merge --admin

      - name: Checkout main after merge
        if: success()
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        
