name: Terraform Deploy on Main

on:
  workflow_run:
    workflows: ["Terraform PR Validation and Auto-Merge"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"

      - name: Initialize Terraform
        run: terraform init

      - name: Download Terraform plan artifact
        uses: actions/download-artifact@v5
        with:
          name: tfplan-pr-${{ github.event.workflow_run.pull_requests[0].head.sha }}

      - name: Apply Terraform changes from PR plan
        run: terraform apply -auto-approve tfplan
